apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storydream

resources:
  - namespace.yaml
  - rbac.yaml
  - workload-identity.yaml
  - frontend.yaml
  - backend.yaml
  - ingress.yaml
  # secrets.yaml - apply separately, not tracked in git
